name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Nếu là project site, thay REPO_NAME bằng tên repo để đặt base path đúng.
      # Nếu là user site (username.github.io), bạn có thể bỏ StaticWebAssetBasePath.
      - name: Publish
        run: |
          dotnet restore
          dotnet publish -c Release -p:UseAppHost=false
          PUBLISH_DIR=$(find . -type d -path "*/bin/Release/*/publish/wwwroot" | head -n 1)
          echo "Publish dir: $PUBLISH_DIR"
          mkdir -p ./_site
          cp -r "$PUBLISH_DIR/"* ./_site/
          ls -la ./_site  # kiểm tra file index.html có tồn tại không

      - name: Add .nojekyll and 404.html
        run: |
          touch ./_site/.nojekyll
          # Fallback routing: copy index.html to 404.html
          cp ./_site/index.html ./_site/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
